
package com.hdfc.generatePolicy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @param newTWCPURL
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GenerateTWTransNo", action = "http://tempuri.org/GenerateTWTransNo")
    @WebResult(name = "GenerateTWTransNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GenerateTWTransNo", targetNamespace = "http://tempuri.org/", className = "com.hdfc.generatePolicy.GenerateTWTransNo")
    @ResponseWrapper(localName = "GenerateTWTransNoResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.generatePolicy.GenerateTWTransNoResponse")
    public String generateTWTransNo(
        @WebParam(name = "NewTWCPURL", targetNamespace = "http://tempuri.org/")
        String newTWCPURL);

}
