
package com.shreeRamGIC;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShriramService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://119.226.131.2/ShriramService/ShriramService.asmx?WSDL")
public class ShriramService
    extends Service
{

    private final static URL SHRIRAMSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHRIRAMSERVICE_EXCEPTION;
    private final static QName SHRIRAMSERVICE_QNAME = new QName("http://tempuri.org/", "ShriramService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://119.226.131.2/ShriramService/ShriramService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHRIRAMSERVICE_WSDL_LOCATION = url;
        SHRIRAMSERVICE_EXCEPTION = e;
    }

    public ShriramService() {
        super(__getWsdlLocation(), SHRIRAMSERVICE_QNAME);
    }

    public ShriramService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHRIRAMSERVICE_QNAME, features);
    }

    public ShriramService(URL wsdlLocation) {
        super(wsdlLocation, SHRIRAMSERVICE_QNAME);
    }

    public ShriramService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHRIRAMSERVICE_QNAME, features);
    }

    public ShriramService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShriramService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShriramServiceSoap
     */
    @WebEndpoint(name = "ShriramServiceSoap")
    public ShriramServiceSoap getShriramServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ShriramServiceSoap"), ShriramServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShriramServiceSoap
     */
    @WebEndpoint(name = "ShriramServiceSoap")
    public ShriramServiceSoap getShriramServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ShriramServiceSoap"), ShriramServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ShriramServiceSoap
     */
    @WebEndpoint(name = "ShriramServiceSoap12")
    public ShriramServiceSoap getShriramServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "ShriramServiceSoap12"), ShriramServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShriramServiceSoap
     */
    @WebEndpoint(name = "ShriramServiceSoap12")
    public ShriramServiceSoap getShriramServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ShriramServiceSoap12"), ShriramServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHRIRAMSERVICE_EXCEPTION!= null) {
            throw SHRIRAMSERVICE_EXCEPTION;
        }
        return SHRIRAMSERVICE_WSDL_LOCATION;
    }

}
