
package com.shreeRamGIC;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShriramServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShriramServiceSoap {


    /**
     * 
     * @param strPrevPolClaimYN
     * @param authHeader
     * @param strPrevPolNCB
     * @param strFirstRegDt
     * @param strADDONCover
     * @param strInsuredState
     * @param strRTOCode
     * @param strPolicyType
     * @param strProductCode
     * @param strVehicleCode
     * @param strPrevPolExpDt
     * @return
     *     returns com.shreeramIns.MPCProposalResponseETT
     */
    @WebMethod(operationName = "GetQuot", action = "http://tempuri.org/GetQuot")
    @WebResult(name = "GetQuotResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetQuot", targetNamespace = "http://tempuri.org/", className = "com.shreeramIns.GetQuot")
    @ResponseWrapper(localName = "GetQuotResponse", targetNamespace = "http://tempuri.org/", className = "com.shreeramIns.GetQuotResponse")
    public MPCProposalResponseETT getQuot(
        @WebParam(name = "strProductCode", targetNamespace = "http://tempuri.org/")
        String strProductCode,
        @WebParam(name = "strPolicyType", targetNamespace = "http://tempuri.org/")
        String strPolicyType,
        @WebParam(name = "strRTOCode", targetNamespace = "http://tempuri.org/")
        String strRTOCode,
        @WebParam(name = "strVehicleCode", targetNamespace = "http://tempuri.org/")
        String strVehicleCode,
        @WebParam(name = "strADDONCover", targetNamespace = "http://tempuri.org/")
        String strADDONCover,
        @WebParam(name = "strFirstRegDt", targetNamespace = "http://tempuri.org/")
        String strFirstRegDt,
        @WebParam(name = "strInsuredState", targetNamespace = "http://tempuri.org/")
        String strInsuredState,
        @WebParam(name = "strPrevPolExpDt", targetNamespace = "http://tempuri.org/")
        String strPrevPolExpDt,
        @WebParam(name = "strPrevPolClaimYN", targetNamespace = "http://tempuri.org/")
        String strPrevPolClaimYN,
        @WebParam(name = "strPrevPolNCB", targetNamespace = "http://tempuri.org/")
        String strPrevPolNCB,
        @WebParam(name = "AuthHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * 
     * @param authHeader
     * @param objPolicyEntryETT
     * @return
     *     returns com.shreeramIns.MPCProposalResponseETT
     */
    @WebMethod(operationName = "GenerateProposal", action = "http://tempuri.org/GenerateProposal")
    @WebResult(name = "GenerateProposalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GenerateProposal", targetNamespace = "http://tempuri.org/", className = "com.shreeramIns.GenerateProposal")
    @ResponseWrapper(localName = "GenerateProposalResponse", targetNamespace = "http://tempuri.org/", className = "com.shreeramIns.GenerateProposalResponse")
    public MPCProposalResponseETT generateProposal(
        @WebParam(name = "objPolicyEntryETT", targetNamespace = "http://tempuri.org/")
        MPCProposalEntryETT objPolicyEntryETT,
        @WebParam(name = "AuthHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * 
     * @param authHeader
     * @param objPolicyApprovalETT
     * @return
     *     returns com.shreeramIns.PolicyApprovalResponseETT
     */
    @WebMethod(operationName = "PolicyApprove", action = "http://tempuri.org/PolicyApprove")
    @WebResult(name = "PolicyApproveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PolicyApprove", targetNamespace = "http://tempuri.org/", className = "com.shreeramIns.PolicyApprove")
    @ResponseWrapper(localName = "PolicyApproveResponse", targetNamespace = "http://tempuri.org/", className = "com.shreeramIns.PolicyApproveResponse")
    public PolicyApprovalResponseETT policyApprove(
        @WebParam(name = "objPolicyApprovalETT", targetNamespace = "http://tempuri.org/")
        PolicyApprovalETT objPolicyApprovalETT,
        @WebParam(name = "AuthHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * 
     * @param authHeader
     * @param strPolSysId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PolicyScheduleURL", action = "http://tempuri.org/PolicyScheduleURL")
    @WebResult(name = "PolicyScheduleURLResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PolicyScheduleURL", targetNamespace = "http://tempuri.org/", className = "com.shreeramIns.PolicyScheduleURL")
    @ResponseWrapper(localName = "PolicyScheduleURLResponse", targetNamespace = "http://tempuri.org/", className = "com.shreeramIns.PolicyScheduleURLResponse")
    public String policyScheduleURL(
        @WebParam(name = "strPolSysId", targetNamespace = "http://tempuri.org/")
        String strPolSysId,
        @WebParam(name = "AuthHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * 
     * @param strPrevPolClaimYN
     * @param authHeader
     * @param strPrevPolNCB
     * @param strVehicleCategory
     * @param strFirstRegDt
     * @param strInsuredState
     * @param strRTOCode
     * @param strPolicyType
     * @param strProductCode
     * @param strVehicleCode
     * @param strPrevPolExpDt
     * @return
     *     returns com.shreeramIns.PCCVProposalResponseETT
     */
    @WebMethod(operationName = "GetQuotCommercial", action = "http://tempuri.org/GetQuotCommercial")
    @WebResult(name = "GetQuotCommercialResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetQuotCommercial", targetNamespace = "http://tempuri.org/", className = "com.shreeramIns.GetQuotCommercial")
    @ResponseWrapper(localName = "GetQuotCommercialResponse", targetNamespace = "http://tempuri.org/", className = "com.shreeramIns.GetQuotCommercialResponse")
    public PCCVProposalResponseETT getQuotCommercial(
        @WebParam(name = "strProductCode", targetNamespace = "http://tempuri.org/")
        String strProductCode,
        @WebParam(name = "strPolicyType", targetNamespace = "http://tempuri.org/")
        String strPolicyType,
        @WebParam(name = "strRTOCode", targetNamespace = "http://tempuri.org/")
        String strRTOCode,
        @WebParam(name = "strVehicleCode", targetNamespace = "http://tempuri.org/")
        String strVehicleCode,
        @WebParam(name = "strVehicleCategory", targetNamespace = "http://tempuri.org/")
        String strVehicleCategory,
        @WebParam(name = "strFirstRegDt", targetNamespace = "http://tempuri.org/")
        String strFirstRegDt,
        @WebParam(name = "strInsuredState", targetNamespace = "http://tempuri.org/")
        String strInsuredState,
        @WebParam(name = "strPrevPolExpDt", targetNamespace = "http://tempuri.org/")
        String strPrevPolExpDt,
        @WebParam(name = "strPrevPolClaimYN", targetNamespace = "http://tempuri.org/")
        String strPrevPolClaimYN,
        @WebParam(name = "strPrevPolNCB", targetNamespace = "http://tempuri.org/")
        String strPrevPolNCB,
        @WebParam(name = "AuthHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * 
     * @param authHeader
     * @param objPolicyEntryETT
     * @return
     *     returns com.shreeramIns.PCCVProposalResponseETT
     */
    @WebMethod(operationName = "GeneratePCCVProposal", action = "http://tempuri.org/GeneratePCCVProposal")
    @WebResult(name = "GeneratePCCVProposalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneratePCCVProposal", targetNamespace = "http://tempuri.org/", className = "com.shreeramIns.GeneratePCCVProposal")
    @ResponseWrapper(localName = "GeneratePCCVProposalResponse", targetNamespace = "http://tempuri.org/", className = "com.shreeramIns.GeneratePCCVProposalResponse")
    public PCCVProposalResponseETT generatePCCVProposal(
        @WebParam(name = "objPolicyEntryETT", targetNamespace = "http://tempuri.org/")
        PCCVProposalEntryETT objPolicyEntryETT,
        @WebParam(name = "AuthHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

}
