
package com.hdfc.generatePolicy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceHttpPost", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceHttpPost {


    /**
     * 
     * @param newTWCPURL
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GenerateTWTransNo")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String generateTWTransNo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "NewTWCPURL")
        String newTWCPURL);

}
