
package com.hdfc.proposal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @param str
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/xmlstring")
    @WebResult(name = "xmlstringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "xmlstring", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.Xmlstring")
    @ResponseWrapper(localName = "xmlstringResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.XmlstringResponse")
    public String xmlstring(
        @WebParam(name = "str", targetNamespace = "http://tempuri.org/")
        String str);

    /**
     * 
     * @param agentCode
     * @param prevPolicyNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HEGICMotorRenewal", action = "http://tempuri.org/HEGICMotorRenewal")
    @WebResult(name = "HEGICMotorRenewalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HEGICMotorRenewal", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewal")
    @ResponseWrapper(localName = "HEGICMotorRenewalResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalResponse")
    public String hegicMotorRenewal(
        @WebParam(name = "AgentCode", targetNamespace = "http://tempuri.org/")
        String agentCode,
        @WebParam(name = "PrevPolicyNo", targetNamespace = "http://tempuri.org/")
        String prevPolicyNo);

    /**
     * 
     * @param pgTransNo
     * @param agentCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBreakinInspectionStatus", action = "http://tempuri.org/GetBreakinInspectionStatus")
    @WebResult(name = "GetBreakinInspectionStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBreakinInspectionStatus", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.GetBreakinInspectionStatus")
    @ResponseWrapper(localName = "GetBreakinInspectionStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.GetBreakinInspectionStatusResponse")
    public String getBreakinInspectionStatus(
        @WebParam(name = "AgentCode", targetNamespace = "http://tempuri.org/")
        String agentCode,
        @WebParam(name = "PGTransNo", targetNamespace = "http://tempuri.org/")
        String pgTransNo);

    /**
     * 
     * @param pgTransNo
     * @param agentCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBreakinProposalDataFinalPremium", action = "http://tempuri.org/GetBreakinProposalDataFinalPremium")
    @WebResult(name = "GetBreakinProposalDataFinalPremiumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBreakinProposalDataFinalPremium", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.GetBreakinProposalDataFinalPremium")
    @ResponseWrapper(localName = "GetBreakinProposalDataFinalPremiumResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.GetBreakinProposalDataFinalPremiumResponse")
    public String getBreakinProposalDataFinalPremium(
        @WebParam(name = "AgentCode", targetNamespace = "http://tempuri.org/")
        String agentCode,
        @WebParam(name = "PGTransNo", targetNamespace = "http://tempuri.org/")
        String pgTransNo);

    /**
     * 
     * @param agentCode
     * @param prevPolicyNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HEGICMotorRenewal_Dynamic", action = "http://tempuri.org/HEGICMotorRenewal_Dynamic")
    @WebResult(name = "HEGICMotorRenewal_DynamicResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HEGICMotorRenewal_Dynamic", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalDynamic")
    @ResponseWrapper(localName = "HEGICMotorRenewal_DynamicResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalDynamicResponse")
    public String hegicMotorRenewalDynamic(
        @WebParam(name = "AgentCode", targetNamespace = "http://tempuri.org/")
        String agentCode,
        @WebParam(name = "PrevPolicyNo", targetNamespace = "http://tempuri.org/")
        String prevPolicyNo);

    /**
     * 
     * @param vehicleRegistratonNo
     * @param agentCode
     * @param prevPolicyNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HEGICMotorRenewal_Extract", action = "http://tempuri.org/HEGICMotorRenewal_Extract")
    @WebResult(name = "HEGICMotorRenewal_ExtractResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HEGICMotorRenewal_Extract", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalExtract")
    @ResponseWrapper(localName = "HEGICMotorRenewal_ExtractResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalExtractResponse")
    public String hegicMotorRenewalExtract(
        @WebParam(name = "AgentCode", targetNamespace = "http://tempuri.org/")
        String agentCode,
        @WebParam(name = "PrevPolicyNo", targetNamespace = "http://tempuri.org/")
        String prevPolicyNo,
        @WebParam(name = "VehicleRegistratonNo", targetNamespace = "http://tempuri.org/")
        String vehicleRegistratonNo);

    /**
     * 
     * @param renewalPremiumInputXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HEGICMotorRenewal_Premium", action = "http://tempuri.org/HEGICMotorRenewal_Premium")
    @WebResult(name = "HEGICMotorRenewal_PremiumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HEGICMotorRenewal_Premium", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalPremium")
    @ResponseWrapper(localName = "HEGICMotorRenewal_PremiumResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalPremiumResponse")
    public String hegicMotorRenewalPremium(
        @WebParam(name = "RenewalPremiumInputXml", targetNamespace = "http://tempuri.org/")
        String renewalPremiumInputXml);

    /**
     * 
     * @param rwxmlDetails
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HEGICMotorRenewal_GenerateRWTransaction", action = "http://tempuri.org/HEGICMotorRenewal_GenerateRWTransaction")
    @WebResult(name = "HEGICMotorRenewal_GenerateRWTransactionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HEGICMotorRenewal_GenerateRWTransaction", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalGenerateRWTransaction")
    @ResponseWrapper(localName = "HEGICMotorRenewal_GenerateRWTransactionResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalGenerateRWTransactionResponse")
    public String hegicMotorRenewalGenerateRWTransaction(
        @WebParam(name = "RWXMLDetails", targetNamespace = "http://tempuri.org/")
        String rwxmlDetails);

    /**
     * 
     * @param renewalInputAddressDetails
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HEGICMotorRenewal_UpdateAddressDetails", action = "http://tempuri.org/HEGICMotorRenewal_UpdateAddressDetails")
    @WebResult(name = "HEGICMotorRenewal_UpdateAddressDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HEGICMotorRenewal_UpdateAddressDetails", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalUpdateAddressDetails")
    @ResponseWrapper(localName = "HEGICMotorRenewal_UpdateAddressDetailsResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalUpdateAddressDetailsResponse")
    public String hegicMotorRenewalUpdateAddressDetails(
        @WebParam(name = "RenewalInputAddressDetails", targetNamespace = "http://tempuri.org/")
        String renewalInputAddressDetails);

    /**
     * 
     * @param agentCode
     * @param vehicleRegistrationNo
     * @param prevPolicyNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HEGICMotorRenewal_GetRenewalPlans", action = "http://tempuri.org/HEGICMotorRenewal_GetRenewalPlans")
    @WebResult(name = "HEGICMotorRenewal_GetRenewalPlansResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HEGICMotorRenewal_GetRenewalPlans", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalGetRenewalPlans")
    @ResponseWrapper(localName = "HEGICMotorRenewal_GetRenewalPlansResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalGetRenewalPlansResponse")
    public String hegicMotorRenewalGetRenewalPlans(
        @WebParam(name = "AgentCode", targetNamespace = "http://tempuri.org/")
        String agentCode,
        @WebParam(name = "PrevPolicyNo", targetNamespace = "http://tempuri.org/")
        String prevPolicyNo,
        @WebParam(name = "VehicleRegistrationNo", targetNamespace = "http://tempuri.org/")
        String vehicleRegistrationNo);

    /**
     * 
     * @param renewalInputXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HEGICTWRenewal_Extract", action = "http://tempuri.org/HEGICTWRenewal_Extract")
    @WebResult(name = "HEGICTWRenewal_ExtractResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HEGICTWRenewal_Extract", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICTWRenewalExtract")
    @ResponseWrapper(localName = "HEGICTWRenewal_ExtractResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICTWRenewalExtractResponse")
    public String hegictwRenewalExtract(
        @WebParam(name = "RenewalInputXml", targetNamespace = "http://tempuri.org/")
        String renewalInputXml);

    /**
     * 
     * @param renewalInputXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HEGICTWRenewal_Premium", action = "http://tempuri.org/HEGICTWRenewal_Premium")
    @WebResult(name = "HEGICTWRenewal_PremiumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HEGICTWRenewal_Premium", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICTWRenewalPremium")
    @ResponseWrapper(localName = "HEGICTWRenewal_PremiumResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICTWRenewalPremiumResponse")
    public String hegictwRenewalPremium(
        @WebParam(name = "RenewalInputXml", targetNamespace = "http://tempuri.org/")
        String renewalInputXml);

    /**
     * 
     * @param renewalInputXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HEGICTWRenewal_GenerateRWTransaction", action = "http://tempuri.org/HEGICTWRenewal_GenerateRWTransaction")
    @WebResult(name = "HEGICTWRenewal_GenerateRWTransactionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HEGICTWRenewal_GenerateRWTransaction", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICTWRenewalGenerateRWTransaction")
    @ResponseWrapper(localName = "HEGICTWRenewal_GenerateRWTransactionResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICTWRenewalGenerateRWTransactionResponse")
    public String hegictwRenewalGenerateRWTransaction(
        @WebParam(name = "RenewalInputXml", targetNamespace = "http://tempuri.org/")
        String renewalInputXml);

    /**
     * 
     * @param renewalInputXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HEGICMotorRenewal_GenerateRWTransactionDirect", action = "http://tempuri.org/HEGICMotorRenewal_GenerateRWTransactionDirect")
    @WebResult(name = "HEGICMotorRenewal_GenerateRWTransactionDirectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HEGICMotorRenewal_GenerateRWTransactionDirect", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalGenerateRWTransactionDirect")
    @ResponseWrapper(localName = "HEGICMotorRenewal_GenerateRWTransactionDirectResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.proposal.HEGICMotorRenewalGenerateRWTransactionDirectResponse")
    public String hegicMotorRenewalGenerateRWTransactionDirect(
        @WebParam(name = "RenewalInputXml", targetNamespace = "http://tempuri.org/")
        String renewalInputXml);

}
