
package com.kotakGic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPartnerIntegrationService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPartnerIntegrationService {


    /**
     * 
     * @param partnerIntegrationXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SavePartner_integration", action = "http://tempuri.org/IPartnerIntegrationService/SavePartner_integration")
    @WebResult(name = "SavePartner_integrationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SavePartner_integration", targetNamespace = "http://tempuri.org/", className = "com.kotak.SavePartnerIntegration")
    @ResponseWrapper(localName = "SavePartner_integrationResponse", targetNamespace = "http://tempuri.org/", className = "com.kotak.SavePartnerIntegrationResponse")
    public String savePartnerIntegration(
        @WebParam(name = "Partner_integrationXML", targetNamespace = "http://tempuri.org/")
        String partnerIntegrationXML);

    /**
     * 
     * @param strPolicyIssueTime
     * @param strTransactionID
     * @param strCustomerName
     * @param strTransactionRef
     * @param strProdType
     * @param strPolicyNo
     * @param strPassword
     * @param strUserId
     * @param strPolicyPDF
     * @return
     *     returns com.kotak.ClsSignPDF
     */
    @WebMethod(operationName = "GetSignPolicyPDF", action = "http://tempuri.org/IPartnerIntegrationService/GetSignPolicyPDF")
    @WebResult(name = "GetSignPolicyPDFResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSignPolicyPDF", targetNamespace = "http://tempuri.org/", className = "com.kotak.GetSignPolicyPDF")
    @ResponseWrapper(localName = "GetSignPolicyPDFResponse", targetNamespace = "http://tempuri.org/", className = "com.kotak.GetSignPolicyPDFResponse")
    public ClsSignPDF getSignPolicyPDF(
        @WebParam(name = "strUserId", targetNamespace = "http://tempuri.org/")
        String strUserId,
        @WebParam(name = "strPassword", targetNamespace = "http://tempuri.org/")
        String strPassword,
        @WebParam(name = "strProdType", targetNamespace = "http://tempuri.org/")
        String strProdType,
        @WebParam(name = "strPolicyNo", targetNamespace = "http://tempuri.org/")
        String strPolicyNo,
        @WebParam(name = "strPolicyIssueTime", targetNamespace = "http://tempuri.org/")
        String strPolicyIssueTime,
        @WebParam(name = "strTransactionID", targetNamespace = "http://tempuri.org/")
        String strTransactionID,
        @WebParam(name = "strTransactionRef", targetNamespace = "http://tempuri.org/")
        String strTransactionRef,
        @WebParam(name = "strCustomerName", targetNamespace = "http://tempuri.org/")
        String strCustomerName,
        @WebParam(name = "strPolicyPDF", targetNamespace = "http://tempuri.org/")
        byte[] strPolicyPDF);

}
