
package com.hdfc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceHttpPost", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceHttpPost {


    /**
     * 
     * @param str
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getIDV(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "str")
        String str);

    /**
     * 
     * @param str
     * @param vehicleClassCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getPremium(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "str")
        String str,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "VehicleClassCode")
        String vehicleClassCode);

    /**
     * 
     * @param str
     * @param vehicleClassCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getPremiumMultiYear(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "str")
        String str,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "VehicleClassCode")
        String vehicleClassCode);

    /**
     * All Date parameters should be passed in dd/MM/yyyy format.
     * 
     * @param policyStartDate
     * @param rtoLocationCode
     * @param businessType
     * @param vehicleModelCode
     * @param agentCode
     * @param firstRegistrationDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPlanTypes")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getPlanTypes(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AgentCode")
        String agentCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "BusinessType")
        String businessType,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "VehicleModelCode")
        String vehicleModelCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "RTOLocationCode")
        String rtoLocationCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "PolicyStartDate")
        String policyStartDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "FirstRegistrationDate")
        String firstRegistrationDate);

}
