
package com.universal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService1", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService1 {


    /**
     * 
     * @param strXdoc
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IService1/commBRIDGEFusionMOTOR")
    @WebResult(name = "commBRIDGEFusionMOTORResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "commBRIDGEFusionMOTOR", targetNamespace = "http://tempuri.org/", className = "com.universal.CommBRIDGEFusionMOTOR")
    @ResponseWrapper(localName = "commBRIDGEFusionMOTORResponse", targetNamespace = "http://tempuri.org/", className = "com.universal.CommBRIDGEFusionMOTORResponse")
    public String commBRIDGEFusionMOTOR(
        @WebParam(name = "strXdoc", targetNamespace = "http://tempuri.org/")
        String strXdoc);

    /**
     * 
     * @param strXdoc
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IService1/commBRIDGEFusionHEALTH")
    @WebResult(name = "commBRIDGEFusionHEALTHResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "commBRIDGEFusionHEALTH", targetNamespace = "http://tempuri.org/", className = "com.universal.CommBRIDGEFusionHEALTH")
    @ResponseWrapper(localName = "commBRIDGEFusionHEALTHResponse", targetNamespace = "http://tempuri.org/", className = "com.universal.CommBRIDGEFusionHEALTHResponse")
    public String commBRIDGEFusionHEALTH(
        @WebParam(name = "strXdoc", targetNamespace = "http://tempuri.org/")
        String strXdoc);

    /**
     * 
     * @param strXdoc
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IService1/commBRIDGEFusionTravel")
    @WebResult(name = "commBRIDGEFusionTravelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "commBRIDGEFusionTravel", targetNamespace = "http://tempuri.org/", className = "com.universal.CommBRIDGEFusionTravel")
    @ResponseWrapper(localName = "commBRIDGEFusionTravelResponse", targetNamespace = "http://tempuri.org/", className = "com.universal.CommBRIDGEFusionTravelResponse")
    public String commBRIDGEFusionTravel(
        @WebParam(name = "strXdoc", targetNamespace = "http://tempuri.org/")
        String strXdoc);

}
