
package com.futureGenerali;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param product
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreatePolicy", action = "http://tempuri.org/IService/CreatePolicy")
    @WebResult(name = "CreatePolicyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreatePolicy", targetNamespace = "http://tempuri.org/", className = "com.futureGenerali.CreatePolicy")
    @ResponseWrapper(localName = "CreatePolicyResponse", targetNamespace = "http://tempuri.org/", className = "com.futureGenerali.CreatePolicyResponse")
    public String createPolicy(
        @WebParam(name = "Product", targetNamespace = "http://tempuri.org/")
        String product,
        @WebParam(name = "XML", targetNamespace = "http://tempuri.org/")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateAndUpdateClient", action = "http://tempuri.org/IService/CreateAndUpdateClient")
    @WebResult(name = "CreateAndUpdateClientResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateAndUpdateClient", targetNamespace = "http://tempuri.org/", className = "com.futureGenerali.CreateAndUpdateClient")
    @ResponseWrapper(localName = "CreateAndUpdateClientResponse", targetNamespace = "http://tempuri.org/", className = "com.futureGenerali.CreateAndUpdateClientResponse")
    public String createAndUpdateClient(
        @WebParam(name = "XML", targetNamespace = "http://tempuri.org/")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateAndUpdateCorporateClient", action = "http://tempuri.org/IService/CreateAndUpdateCorporateClient")
    @WebResult(name = "CreateAndUpdateCorporateClientResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateAndUpdateCorporateClient", targetNamespace = "http://tempuri.org/", className = "com.futureGenerali.CreateAndUpdateCorporateClient")
    @ResponseWrapper(localName = "CreateAndUpdateCorporateClientResponse", targetNamespace = "http://tempuri.org/", className = "com.futureGenerali.CreateAndUpdateCorporateClientResponse")
    public String createAndUpdateCorporateClient(
        @WebParam(name = "XML", targetNamespace = "http://tempuri.org/")
        String xml);

    /**
     * 
     * @param product
     * @param multiReceipt
     * @param xml
     * @param payerID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreatePolicyWithPayer", action = "http://tempuri.org/IService/CreatePolicyWithPayer")
    @WebResult(name = "CreatePolicyWithPayerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreatePolicyWithPayer", targetNamespace = "http://tempuri.org/", className = "com.futureGenerali.CreatePolicyWithPayer")
    @ResponseWrapper(localName = "CreatePolicyWithPayerResponse", targetNamespace = "http://tempuri.org/", className = "com.futureGenerali.CreatePolicyWithPayerResponse")
    public String createPolicyWithPayer(
        @WebParam(name = "Product", targetNamespace = "http://tempuri.org/")
        String product,
        @WebParam(name = "XML", targetNamespace = "http://tempuri.org/")
        String xml,
        @WebParam(name = "PayerID", targetNamespace = "http://tempuri.org/")
        String payerID,
        @WebParam(name = "multiReceipt", targetNamespace = "http://tempuri.org/")
        String multiReceipt);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateOnlyReceipt", action = "http://tempuri.org/IService/CreateOnlyReceipt")
    @WebResult(name = "CreateOnlyReceiptResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateOnlyReceipt", targetNamespace = "http://tempuri.org/", className = "com.futureGenerali.CreateOnlyReceipt")
    @ResponseWrapper(localName = "CreateOnlyReceiptResponse", targetNamespace = "http://tempuri.org/", className = "com.futureGenerali.CreateOnlyReceiptResponse")
    public String createOnlyReceipt(
        @WebParam(name = "XML", targetNamespace = "http://tempuri.org/")
        String xml);

    /**
     * 
     * @param pincode
     * @return
     *     returns com.futureGenerali.FetchPinCodeResponse.FetchPinCodeResult
     */
    @WebMethod(operationName = "FetchPinCode", action = "http://tempuri.org/IService/FetchPinCode")
    @WebResult(name = "FetchPinCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FetchPinCode", targetNamespace = "http://tempuri.org/", className = "com.futureGenerali.FetchPinCode")
    @ResponseWrapper(localName = "FetchPinCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.futureGenerali.FetchPinCodeResponse")
    public com.futureGenerali.FetchPinCodeResponse.FetchPinCodeResult fetchPinCode(
        @WebParam(name = "Pincode", targetNamespace = "http://tempuri.org/")
        String pincode);

    /**
     * 
     * @param policyno
     * @return
     *     returns com.futureGenerali.IsClaimResponse.IsClaimResult
     */
    @WebMethod(action = "http://tempuri.org/IService/isClaim")
    @WebResult(name = "isClaimResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "isClaim", targetNamespace = "http://tempuri.org/", className = "com.futureGenerali.IsClaim")
    @ResponseWrapper(localName = "isClaimResponse", targetNamespace = "http://tempuri.org/", className = "com.futureGenerali.IsClaimResponse")
    public com.futureGenerali.IsClaimResponse.IsClaimResult isClaim(
        @WebParam(name = "policyno", targetNamespace = "http://tempuri.org/")
        String policyno);

}
