
package com.kotakGic;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PartnerIntegrationService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://kgibridgeuat.kotakmahindrageneralinsurance.com/GCIntegrationServices/PartnerIntegrationService.svc?wsdl")
public class PartnerIntegrationService
    extends Service
{

    private final static URL PARTNERINTEGRATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PARTNERINTEGRATIONSERVICE_EXCEPTION;
    private final static QName PARTNERINTEGRATIONSERVICE_QNAME = new QName("http://tempuri.org/", "PartnerIntegrationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://kgibridgeuat.kotakmahindrageneralinsurance.com/GCIntegrationServices/PartnerIntegrationService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARTNERINTEGRATIONSERVICE_WSDL_LOCATION = url;
        PARTNERINTEGRATIONSERVICE_EXCEPTION = e;
    }

    public PartnerIntegrationService() {
        super(__getWsdlLocation(), PARTNERINTEGRATIONSERVICE_QNAME);
    }

    public PartnerIntegrationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARTNERINTEGRATIONSERVICE_QNAME, features);
    }

    public PartnerIntegrationService(URL wsdlLocation) {
        super(wsdlLocation, PARTNERINTEGRATIONSERVICE_QNAME);
    }

    public PartnerIntegrationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARTNERINTEGRATIONSERVICE_QNAME, features);
    }

    public PartnerIntegrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartnerIntegrationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IPartnerIntegrationService
     */
    @WebEndpoint(name = "BasicHttpBinding_IPartnerIntegrationService")
    public IPartnerIntegrationService getBasicHttpBindingIPartnerIntegrationService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IPartnerIntegrationService"), IPartnerIntegrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPartnerIntegrationService
     */
    @WebEndpoint(name = "BasicHttpBinding_IPartnerIntegrationService")
    public IPartnerIntegrationService getBasicHttpBindingIPartnerIntegrationService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IPartnerIntegrationService"), IPartnerIntegrationService.class, features);
    }

    /**
     * 
     * @return
     *     returns IPartnerIntegrationService
     */
    @WebEndpoint(name = "BasicHttpsBinding_IPartnerIntegrationService")
    public IPartnerIntegrationService getBasicHttpsBindingIPartnerIntegrationService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpsBinding_IPartnerIntegrationService"), IPartnerIntegrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPartnerIntegrationService
     */
    @WebEndpoint(name = "BasicHttpsBinding_IPartnerIntegrationService")
    public IPartnerIntegrationService getBasicHttpsBindingIPartnerIntegrationService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpsBinding_IPartnerIntegrationService"), IPartnerIntegrationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARTNERINTEGRATIONSERVICE_EXCEPTION!= null) {
            throw PARTNERINTEGRATIONSERVICE_EXCEPTION;
        }
        return PARTNERINTEGRATIONSERVICE_WSDL_LOCATION;
    }

}
