
package com.bajajAllianz;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServicePolicy", targetNamespace = "http://com/bajajallianz/motWebPolicy/WebServicePolicy.wsdl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServicePolicy {


    /**
     * 
     * @param paddoncoverListInout
     * @param accessoriesListInout
     * @param pContactNo
     * @param pTransactionType
     * @param pTransactionIdInout
     * @param pErrorCodeOut
     * @param pWeoMotPolicyInInout
     * @param pDetariffObjInout
     * @param premiumSummeryListOut
     * @param premiumDetailsOutOut
     * @param pCity
     * @param motExtraCover
     * @param pQuestListInout
     * @param pErrorOut
     * @param pVehicleCode
     * @param pUserId
     * @param pPassword
     */
    @WebMethod(action = "http://com/bajajallianz/motWebPolicy/WebServicePolicy.wsdl/calculateMotorPremiumSig")
    public void calculateMotorPremiumSig(
        @WebParam(name = "pUserId", partName = "pUserId")
        String pUserId,
        @WebParam(name = "pPassword", partName = "pPassword")
        String pPassword,
        @WebParam(name = "pVehicleCode", partName = "pVehicleCode")
        BigDecimal pVehicleCode,
        @WebParam(name = "pCity", partName = "pCity")
        String pCity,
        @WebParam(name = "pWeoMotPolicyIn_inout", mode = WebParam.Mode.INOUT, partName = "pWeoMotPolicyIn_inout")
        Holder<WeoMotPlanDetailsUser> pWeoMotPolicyInInout,
        @WebParam(name = "accessoriesList_inout", mode = WebParam.Mode.INOUT, partName = "accessoriesList_inout")
        Holder<WeoMotAccessoriesUserArray> accessoriesListInout,
        @WebParam(name = "paddoncoverList_inout", mode = WebParam.Mode.INOUT, partName = "paddoncoverList_inout")
        Holder<WeoMotGenParamUserArray> paddoncoverListInout,
        @WebParam(name = "motExtraCover", partName = "motExtraCover")
        WeoSigMotExtraCoversUser motExtraCover,
        @WebParam(name = "pQuestList_inout", mode = WebParam.Mode.INOUT, partName = "pQuestList_inout")
        Holder<WeoBjazMotQuestionaryUserArray> pQuestListInout,
        @WebParam(name = "pDetariffObj_inout", mode = WebParam.Mode.INOUT, partName = "pDetariffObj_inout")
        Holder<WeoMotDetariffObjUser> pDetariffObjInout,
        @WebParam(name = "premiumDetailsOut_out", mode = WebParam.Mode.INOUT, partName = "premiumDetailsOut_out")
        Holder<WeoMotPremiumDetailsUser> premiumDetailsOutOut,
        @WebParam(name = "premiumSummeryList_out", mode = WebParam.Mode.INOUT, partName = "premiumSummeryList_out")
        Holder<WeoMotPremiumSummaryUserArray> premiumSummeryListOut,
        @WebParam(name = "pError_out", mode = WebParam.Mode.INOUT, partName = "pError_out")
        Holder<WeoTygeErrorMessageUserArray> pErrorOut,
        @WebParam(name = "pErrorCode_out", mode = WebParam.Mode.INOUT, partName = "pErrorCode_out")
        Holder<BigDecimal> pErrorCodeOut,
        @WebParam(name = "pTransactionId_inout", mode = WebParam.Mode.INOUT, partName = "pTransactionId_inout")
        Holder<BigDecimal> pTransactionIdInout,
        @WebParam(name = "pTransactionType", partName = "pTransactionType")
        String pTransactionType,
        @WebParam(name = "pContactNo", partName = "pContactNo")
        String pContactNo);

    /**
     * 
     * @param pPolicyRefOut
     * @param pTransactionIdInout
     * @param pErrorCodeOut
     * @param pErrorMsgOut
     * @param pPaymentTransObjInout
     * @param pUserId
     * @param pPassword
     */
    @WebMethod(action = "http://com/bajajallianz/motWebPolicy/WebServicePolicy.wsdl/getPgTransStatus")
    public void getPgTransStatus(
        @WebParam(name = "pUserId", partName = "pUserId")
        String pUserId,
        @WebParam(name = "pPassword", partName = "pPassword")
        String pPassword,
        @WebParam(name = "pTransactionId_inout", mode = WebParam.Mode.INOUT, partName = "pTransactionId_inout")
        Holder<BigDecimal> pTransactionIdInout,
        @WebParam(name = "pPaymentTransObj_inout", mode = WebParam.Mode.INOUT, partName = "pPaymentTransObj_inout")
        Holder<WeoRecStrings40User> pPaymentTransObjInout,
        @WebParam(name = "pPolicyRef_out", mode = WebParam.Mode.INOUT, partName = "pPolicyRef_out")
        Holder<String> pPolicyRefOut,
        @WebParam(name = "pErrorMsg_out", mode = WebParam.Mode.INOUT, partName = "pErrorMsg_out")
        Holder<String> pErrorMsgOut,
        @WebParam(name = "pErrorCode_out", mode = WebParam.Mode.INOUT, partName = "pErrorCode_out")
        Holder<BigDecimal> pErrorCodeOut);

    /**
     * 
     * @param pCustDetailsInout
     * @param pErrorOut
     * @param pErrorCodeOut
     * @param pWeoMotPolicyInInout
     * @param pUserId
     * @param pMotExtraCoverInout
     * @param pPassword
     */
    @WebMethod(action = "http://com/bajajallianz/motWebPolicy/WebServicePolicy.wsdl/getRnwData")
    public void getRnwData(
        @WebParam(name = "pUserId", partName = "pUserId")
        String pUserId,
        @WebParam(name = "pPassword", partName = "pPassword")
        String pPassword,
        @WebParam(name = "pWeoMotPolicyIn_inout", mode = WebParam.Mode.INOUT, partName = "pWeoMotPolicyIn_inout")
        Holder<WeoMotPlanDetailsUser> pWeoMotPolicyInInout,
        @WebParam(name = "pMotExtraCover_inout", mode = WebParam.Mode.INOUT, partName = "pMotExtraCover_inout")
        Holder<WeoSigMotExtraCoversUser> pMotExtraCoverInout,
        @WebParam(name = "pCustDetails_inout", mode = WebParam.Mode.INOUT, partName = "pCustDetails_inout")
        Holder<WeoB2CCustDetailsUser> pCustDetailsInout,
        @WebParam(name = "pError_out", mode = WebParam.Mode.INOUT, partName = "pError_out")
        Holder<WeoTygeErrorMessageUserArray> pErrorOut,
        @WebParam(name = "pErrorCode_out", mode = WebParam.Mode.INOUT, partName = "pErrorCode_out")
        Holder<BigDecimal> pErrorCodeOut);

    /**
     * 
     * @param premiumSummeryList
     * @param premiumDetails
     * @param pErrorCodeOut
     * @param pMotDetariff
     * @param pWeoMotPolicyInInout
     * @param pRcptListInout
     * @param paddoncoverList
     * @param potherdetails
     * @param motExtraCoverInout
     * @param pCustDetailsInout
     * @param ppolicyrefOut
     * @param ppolicyissuedateOut
     * @param paymentmode
     * @param pTransactionId
     * @param pErrorOut
     * @param accessoriesList
     * @param pQuestList
     * @param pUserId
     * @param ppremiumpayerid
     * @param pPassword
     * @param ppartIdOut
     */
    @WebMethod(action = "http://com/bajajallianz/motWebPolicy/WebServicePolicy.wsdl/issuePolicy")
    public void issuePolicy(
        @WebParam(name = "pUserId", partName = "pUserId")
        String pUserId,
        @WebParam(name = "pPassword", partName = "pPassword")
        String pPassword,
        @WebParam(name = "pTransactionId", partName = "pTransactionId")
        BigDecimal pTransactionId,
        @WebParam(name = "pRcptList_inout", mode = WebParam.Mode.INOUT, partName = "pRcptList_inout")
        Holder<WeoTyacPayRowWsUserArray> pRcptListInout,
        @WebParam(name = "pCustDetails_inout", mode = WebParam.Mode.INOUT, partName = "pCustDetails_inout")
        Holder<WeoB2CCustDetailsUser> pCustDetailsInout,
        @WebParam(name = "pWeoMotPolicyIn_inout", mode = WebParam.Mode.INOUT, partName = "pWeoMotPolicyIn_inout")
        Holder<WeoMotPlanDetailsUser> pWeoMotPolicyInInout,
        @WebParam(name = "accessoriesList", partName = "accessoriesList")
        WeoMotAccessoriesUserArray accessoriesList,
        @WebParam(name = "paddoncoverList", partName = "paddoncoverList")
        WeoMotGenParamUserArray paddoncoverList,
        @WebParam(name = "motExtraCover_inout", mode = WebParam.Mode.INOUT, partName = "motExtraCover_inout")
        Holder<WeoSigMotExtraCoversUser> motExtraCoverInout,
        @WebParam(name = "premiumDetails", partName = "premiumDetails")
        WeoMotPremiumDetailsUser premiumDetails,
        @WebParam(name = "premiumSummeryList", partName = "premiumSummeryList")
        WeoMotPremiumSummaryUserArray premiumSummeryList,
        @WebParam(name = "pQuestList", partName = "pQuestList")
        WeoBjazMotQuestionaryUserArray pQuestList,
        @WebParam(name = "ppolicyref_out", mode = WebParam.Mode.INOUT, partName = "ppolicyref_out")
        Holder<String> ppolicyrefOut,
        @WebParam(name = "ppolicyissuedate_out", mode = WebParam.Mode.INOUT, partName = "ppolicyissuedate_out")
        Holder<String> ppolicyissuedateOut,
        @WebParam(name = "ppartId_out", mode = WebParam.Mode.INOUT, partName = "ppartId_out")
        Holder<String> ppartIdOut,
        @WebParam(name = "pError_out", mode = WebParam.Mode.INOUT, partName = "pError_out")
        Holder<WeoTygeErrorMessageUserArray> pErrorOut,
        @WebParam(name = "pErrorCode_out", mode = WebParam.Mode.INOUT, partName = "pErrorCode_out")
        Holder<BigDecimal> pErrorCodeOut,
        @WebParam(name = "ppremiumpayerid", partName = "ppremiumpayerid")
        BigDecimal ppremiumpayerid,
        @WebParam(name = "paymentmode", partName = "paymentmode")
        String paymentmode,
        @WebParam(name = "potherdetails", partName = "potherdetails")
        WeoSigOtherDetailsUser potherdetails,
        @WebParam(name = "pMotDetariff", partName = "pMotDetariff")
        WeoMotDetariffObjUser pMotDetariff);

}
