
package com.hdfc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @param str
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getIDV")
    @WebResult(name = "getIDVResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getIDV", targetNamespace = "http://tempuri.org/", className = "com.hdfc.GetIDV")
    @ResponseWrapper(localName = "getIDVResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.GetIDVResponse")
    public String getIDV(
        @WebParam(name = "str", targetNamespace = "http://tempuri.org/")
        String str);

    /**
     * 
     * @param str
     * @param vehicleClassCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getPremium")
    @WebResult(name = "getPremiumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getPremium", targetNamespace = "http://tempuri.org/", className = "com.hdfc.GetPremium")
    @ResponseWrapper(localName = "getPremiumResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.GetPremiumResponse")
    public String getPremium(
        @WebParam(name = "str", targetNamespace = "http://tempuri.org/")
        String str,
        @WebParam(name = "VehicleClassCode", targetNamespace = "http://tempuri.org/")
        int vehicleClassCode);

    /**
     * 
     * @param str
     * @param vehicleClassCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getPremiumMultiYear")
    @WebResult(name = "getPremiumMultiYearResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getPremiumMultiYear", targetNamespace = "http://tempuri.org/", className = "com.hdfc.GetPremiumMultiYear")
    @ResponseWrapper(localName = "getPremiumMultiYearResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.GetPremiumMultiYearResponse")
    public String getPremiumMultiYear(
        @WebParam(name = "str", targetNamespace = "http://tempuri.org/")
        String str,
        @WebParam(name = "VehicleClassCode", targetNamespace = "http://tempuri.org/")
        int vehicleClassCode);

    /**
     * All Date parameters should be passed in dd/MM/yyyy format.
     * 
     * @param policyStartDate
     * @param rtoLocationCode
     * @param businessType
     * @param vehicleModelCode
     * @param agentCode
     * @param firstRegistrationDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPlanTypes", action = "http://tempuri.org/GetPlanTypes")
    @WebResult(name = "GetPlanTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPlanTypes", targetNamespace = "http://tempuri.org/", className = "com.hdfc.GetPlanTypes")
    @ResponseWrapper(localName = "GetPlanTypesResponse", targetNamespace = "http://tempuri.org/", className = "com.hdfc.GetPlanTypesResponse")
    public String getPlanTypes(
        @WebParam(name = "AgentCode", targetNamespace = "http://tempuri.org/")
        String agentCode,
        @WebParam(name = "BusinessType", targetNamespace = "http://tempuri.org/")
        String businessType,
        @WebParam(name = "VehicleModelCode", targetNamespace = "http://tempuri.org/")
        String vehicleModelCode,
        @WebParam(name = "RTOLocationCode", targetNamespace = "http://tempuri.org/")
        String rtoLocationCode,
        @WebParam(name = "PolicyStartDate", targetNamespace = "http://tempuri.org/")
        String policyStartDate,
        @WebParam(name = "FirstRegistrationDate", targetNamespace = "http://tempuri.org/")
        String firstRegistrationDate);

}
